### ISSUE TITLE
Unable to obtain `xxx.lhr.life`

### ISSUE THREAD

**Issue by iamxiaojianzheng** [azratul/live-share.nvim#5]
After executing `ssh -o StrictHostKeyChecking=no -R 80:localhost:9876 nokey@localhost.run > /tmp/service.url 2>/dev/null & echo $! > /tmp/service.pid`

The content in the /tmp/service.url is missing, so unable to obtain `xxx.lhr.life`
```
authenticated as anonymous user
b27dfd9601c509.lhr.life tunneled with tls termination, https://b27dfd9601c509.lhr.life
create an account and add your key for a longer lasting domain name. see https://localhost.run/docs/forever-free/ for more information.
Open your tunnel address on your mobile with this QR:
```

Bug  executing `ssh -o StrictHostKeyChecking=no -R 80:localhost:9876 nokey@localhost.run > /tmp/service.url` is ok, `/tmp/service.url` contains `xxx.lhr.life`

My environment is Windows+GitBash+WindowsTerminal+Neovim

**Comment by azratul** [comment]
I'm not a Windows user, so I can't offer a fully comprehensive solution, but I've added some code in the test branch that theoretically should work with PowerShell. I spun up a VM to test it, and while it works sometimes, there are occasions when it doesn't. You may need to disable several security policies and properly configure the firewall for it to function consistently.

However, the client mode (LiveShareJoin) works flawlessly on Windows, so I'd recommend using that mode for now if you're on Windows.

If there's anyone in the community with more experience in PowerShell who can contribute to improving Windows compatibility, your help would be greatly appreciated.

Try with this config:

```
      "azratul/live-share.nvim",
      commit = "54203d6f4b02690ff412945ba7d434c6c7062f3c", -- <-- Test branch
      dependencies = {
        "jbyuki/instant.nvim",
      },
      config = function()
        vim.g.instant_username = "your-username"
        require("live-share").setup({
          port_internal = YOUR-PORT,
          max_attempts = 40,
          service = "nokey@localhost.run",
	  service_url = "/YOUR/PATH/service.url",
          service_pid = "/YOUR/PATH/service.pid",
        })
```

**Comment by iamxiaojianzheng** [comment]
work nice
